### ISSUE TITLE
Increment niapy version

### ISSUE THREAD

**Issue by firefly-cpp** [timzatko/Sklearn-Nature-Inspired-Algorithms#22]
Recent changes: https://github.com/NiaOrg/NiaPy/compare/2.0.2...2.0.4

**Comment by firefly-cpp** [comment]
@timzatko

**Comment by timzatko** [comment]
@firefly-cpp updated https://github.com/timzatko/Sklearn-Nature-Inspired-Algorithms/releases/tag/v0.12.0

**Comment by timzatko** [comment]
Closing
