### ISSUE TITLE
How to select optimum parameters?

### ISSUE THREAD

**Issue by hanzigs** [timzatko/Sklearn-Nature-Inspired-Algorithms#3]
Hi,
How should we select the optimum parameters on
```
algorithm : 'ba','hba','fa','hsaba','gwo'
population_size: int, default=50. 
max_n_gen: int, default=100. 
runs: int, default=3. 
max_stagnating_gen: int, default=20. 
```
That's is what is the effect of
population_size  high value and low value
max_n_gen high value and low value
runs high value and low value
max_stagnating_gen high value and low value
Thanks

**Comment by timzatko** [comment]
Hi! Sorry for the late answer. I have updated the docs https://sklearn-nature-inspired-algorithms.readthedocs.io/en/latest/introduction/nature-inspired-search-cv.html

**Comment by hanzigs** [comment]
Thanks for the updates
