### ISSUE TITLE
GPU usage is not full?

### ISSUE THREAD

**Issue by hanzigs** [timzatko/Sklearn-Nature-Inspired-Algorithms#5]
Hi,
Having tf 2.3.0 and keras 2.4.3
NatureInspiredSearchCV not using full GPU
```
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
BatchSize = [100,200,300,400,500,600,700,800,900,1000]
Epochs = [100,200,300,400,500,600,700,800,900,1000]

    def create_model():
    	model = Sequential()
    	model.add(Dense(int(num_cols/2), input_dim=num_cols, activation='relu'))
    	model.add(Dense(1, activation='sigmoid'))
    	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    	return model
    model = KerasClassifier(build_fn=create_model, verbose=0)
    param_grid = dict(batch_size=BatchSize , epochs=Epochs )
    grid = NatureInspiredSearchCV(model, cv = 3, param_grid=param_grid, verbose=0,  algorithm='ba',  population_size=25,  max_n_gen=100,  max_stagnating_gen=10, runs=5, scoring='accuracy', random_state=42)
    grid_result = grid.fit(X_train, y_train)         
    best_hyperparameters = grid_result.best_params_
```
GPU usage is nearly 1-2% all time
![image](https://user-images.githubusercontent.com/30790120/94322546-3d9cec80-ffd6-11ea-9249-c1c29de48c58.png)

i have set
```
from tensorflow.python.client import device_lib
assert 'GPU' in str(device_lib.list_local_devices())
```
Does NatureInspiredSearchCV use n_jobs parameter like GridSearchCV?

**Comment by timzatko** [comment]
Yes, the n_jobs parameter is used, I have updated the docs with the explanation of how. NatureInspiredSearchCV runs on CPU not GPU.

> n_jobs: int, default=None. Number of jobs to run in parallel. None means 1 unless in a joblib.parallel_backend context. -1 means using all processors. This affects the number of jobs when evaluating a model for one _individual_ (for one individual there might be more model evaluations because of cross-validation) not for the whole population - current implementations of nature-inspired algorithms do not support multiprocessing. You will benefit from multiprocessing only if you use cross-validation.
