### ISSUE TITLE
k-fold cross-validation error

### ISSUE THREAD

**Issue by korayaykor** [timzatko/Sklearn-Nature-Inspired-Algorithms#8]
Hi timzatko,  i am currently working on a optimization project. I am using your tutorial as a start point but i am getting this error. I am new to ML , i looked web for a solution but i failed.

`clf = RandomForestClassifier(random_state=42)

nia_search = NatureInspiredSearchCV(

    clf,
    param_grid,
    cv=5,
    verbose=0,
    algorithm='ba',
    population_size=25,
    max_n_gen=100,
    max_stagnating_gen=10,    
    runs=5,
    scoring='f1_macro',
    random_state=42,
  )

nia_search.fit(X_train, y_train)`

when i run this piece of code i got this error.

`/opt/anaconda3/envs/data-mining/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass scoring=f1_macro, n_jobs=None, refit=deprecated, cv=True, verbose=5, pre_dispatch=0, error_score=2*n_jobs, return_train_score=nan as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "

Any idea or comment how to solve this?

Versions of lib
sklearn-nature-inspired-algorithm 0.5.1
sklearn 0.24.2

Screenshots

<img width="1108" alt="Ekran Resmi 2021-05-03 15 17 30" src="https://user-images.githubusercontent.com/36260358/116874913-c04bf100-ac22-11eb-952f-fda570f7b06f.png">
<img width="1005" alt="Ekran Resmi 2021-05-03 15 17 38" src="https://user-images.githubusercontent.com/36260358/116874916-c17d1e00-ac22-11eb-914c-dbd4a2ac384a.png">

**Comment by korayaykor** [comment]
Problem was version of sklearn-nature-inspired-algorithm 0.5.1 downgraded to 0.4.3. Problem solved.

**Comment by timzatko** [comment]
Hi! It is fixed in 0.5.2.
