### ISSUE TITLE
The NiaPy import is lower-case (“niapy”) starting with 2.0.0rc15

### ISSUE THREAD

**Issue by musicinmybrain** [timzatko/Sklearn-Nature-Inspired-Algorithms#9]
This is just a heads-up that the import for NiaPy [is now lower-cased](https://github.com/NiaOrg/NiaPy/commit/3bb12864f5e68b4a7d202ce58ca9e228216e7a90). Currently, this project pins 2.0.0rc10, which precedes the change. When a later version needs to be supported, all of the imports will need to be adjusted from `NiaPy` to `niapy`.

(This came up [downstream in Fedora Linux](https://bugzilla.redhat.com/show_bug.cgi?id=1969131), where pinning a specific dependency version is not an option. I am not the maintainer of that package, just an interested party.)

**Comment by firefly-cpp** [comment]
Thanks @musicinmybrain. You are right. niapy interface for the representation of problems has recently undergone to major revision. There are several interface changes. This is probably the final change of niapy interface. 

@timzatko are you interested to make your package consistent with the latest niapy release?

**Comment by timzatko** [comment]
@firefly-cpp yes, I will make an update.
